openapi: 3.0.3

info:
  title: Mancala API Specification for game manipulation
  description: Mancala game API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: game
    description: Game related operations

paths:
  /game/move:
    post:
      tags:
        - game
      description: Processes a move made by player
      operationId: makeGameMove
      requestBody:
        description: Information about the move - player ID, cup's number
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameMove'
        required: true
      responses:
        '200':
          description: Game status after the move
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameMoveResult'
        default:
          description: 4xx, 5xx Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GameMove:
      type: object
      properties:
        playerId:
          type: string
        cupNumber:
          type: integer
      required:
        - playerId
        - cupNumber
    GameMoveResult:
      type: object
      properties:
        gameStatus:
          $ref: '#/components/schemas/GameStatus'
        nextPlayerId:
          type: string
        winPlayerId:
          type: string
    GameStatus:
      type: string
      enum:
        - ACTIVE
        - DRAW
        - WIN
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
